### ISSUE TITLE
Sendgrid API Error

### ISSUE THREAD

**Issue by tiefenb** [theGC/WireMailSendGrid#1]
I am always getting this error with this code:

$m->to("test@test.at",  $company->title, null, "LEAD: $firstname $lastname");
$m->bcc("xyz@erer.at", $company->title, null, "LEAD: $firstname $lastname");
$m->setTemplateId("...my-template-id....");
$m->setDynamicTemplateData("firstName", $firstname);
$m->setDynamicTemplateData("lastName", $lastname);

400: {"errors":[{"message":"Invalid type. Expected: array, given: object.","field":"personalizations","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Personalizations-Errors"}]}

**Comment by theGC** [comment]
just pushed a new version 1.1.1 which should fix this.
